### ISSUE TITLE
Emit events at important points

### ISSUE THREAD

**Issue by MartinRoss-IBM** [logdna/nodejs#49] opened 2019-05-13 15:16 UTC
Currently when an error occurs, such as on flush, and other points debug is used to output information - ie.
https://github.com/logdna/nodejs/blob/master/lib/logger.js#L254

However, as a user of the library I would like to take action if this occurs - such as emit a custom metric or trigger some operational response if it continues to occur.

A solution would be to emit events:
https://nodejs.org/docs/latest-v10.x/api/events.html

Some points I initially promose to emit events from would be:
- https://github.com/logdna/nodejs/blob/master/lib/logger.js#L240
- https://github.com/logdna/nodejs/blob/master/lib/logger.js#L249
- https://github.com/logdna/nodejs/blob/master/lib/logger.js#L254

**Comment by smusali** [comment] 2019-06-20 00:12
@MartinRoss-IBM, can you give an example? Also, since we have updated the codebase after you posted this, links may show the wrong lines.

That'd be great, if you can give us an example and we can think of what we can do for improving this.

Thanks in advance!

**Comment by andyedwardsibm** [comment] 2019-07-25 14:18
The primary case is for any code in `Logger.prototype._flush()` that would call the callback with an error to also emit an event.  Could this:
- emit an 'error' event with the error message
- emit a 'dropped' event to indicate that logs have been dropped.  I'm assuming this is true as I can't see any retry logic, and `_flush()` clears out the buffer, so it looks like any failing call will lose the logs.

Essentially, we want a hook for when something goes wrong in the library, as at the moment in production environments, the code fails silently and with nothing we can use as a trigger for alerting the operators of a problem.

**Comment by smusali** [comment] 2019-08-01 15:44
@andyedwardsdfdl that's nice suggestion and thanks for that! We have also been thinking about providing option to buffer the logs into files in the case of network issues - we should discuss and scope out the solution first! Will get back to you asap! Thanks again!

**Comment by vilyapilya** [comment] 2019-08-02 19:45
Hi @andyedwardsdfdl thank you again for giving us your feedback. We have fixed this issue in our recent update: https://github.com/logdna/nodejs/commit/8a2a77196b71488160e78b28ba721c6c2820d020 

Please reach out to us if you have more questions, concerns or suggestions.

**Comment by andyedwardsibm** [comment] 2019-08-08 09:25
Sorry to be a pain, but I'm not sure that PR addresses the original concern.  We are actually using https://github.com/logdna/logdna-bunyan.  With https://github.com/logdna/nodejs/commit/8a2a77196b71488160e78b28ba721c6c2820d020 I cannot see how I can be notified of an error.  I don't have the ability to set any of the callbacks that are passed to `_flush` or `flushAll`.

**Comment by amrothabet** [comment] 2019-09-11 13:56
Hey @smusali @vilyapilya we're still trying to figure out how we can provide our own callback to the flush function since currently there is no way to provide it when you create a new logger. It would be great if we can at least provide our own callback in the Logger function:
https://github.com/logdna/nodejs/blob/a8ae4263a75b507fc5be913359113d1c099153b7/lib/logger.js#L45
***
Currently, the callback is automatically set to some error debugging functions https://github.com/logdna/nodejs/blob/a8ae4263a75b507fc5be913359113d1c099153b7/lib/logger.js#L255
https://github.com/logdna/nodejs/blob/a8ae4263a75b507fc5be913359113d1c099153b7/lib/logger.js#L266
https://github.com/logdna/nodejs/blob/a8ae4263a75b507fc5be913359113d1c099153b7/lib/logger.js#L273

**Comment by vilyapilya** [comment] 2019-09-12 04:57
@andyedwardsdfdl, @amrothabet I see that you want to have a custom error and exception handling in all cases and not only when you use _flush/flushAll functions directly. We have been considering to enhance our exception handling by giving it further flexibility and we will work on it soon. Currently, our library takes a timeout and retains the logs in the buffer in case of failing to send the logs. The timeout period and the retaining limit are both configurable. 
We appreciate your feedback.

**Comment by vilyapilya** [comment] 2019-09-12 06:51
Actually, I think I overcomplicated. I have created a merge request that adds a callback to logging functionality.

**Comment by amrothabet** [comment] 2019-09-12 09:43
> @andyedwardsdfdl, @amrothabet I see that you want to have a custom error and exception handling in all cases and not only when you use _flush/flushAll functions directly. We have been considering to enhance our exception handling by giving it further flexibility and we will work on it soon. Currently, our library takes a timeout and retains the logs in the buffer in case of failing to send the logs. The timeout period and the retaining limit are both configurable.
> We appreciate your feedback.

@vilyapilya I think having custom error and exception handling would be the perfect thing for us so that we could identify what specific issue occurred during logging and handle it specifically.

> Actually, I think I overcomplicated. I have created a merge request that adds a callback to logging functionality.

Adding a callback to the logging functionality allows us to know that an issue occurred during flushing, but not what specifically happened wrong (unless we pattern match the error message, which wouldn't be a good idea since the error message might change in a later build)

**Comment by amrothabet** [comment] 2019-09-23 09:27
@smusali @vilyapilya Any updates on this issue please?

**Comment by vilyapilya** [comment] 2020-01-02 22:46
@amrothabet the issue is addressed in the current code.

**Comment by andyedwardsibm** [comment] 2020-01-28 16:06
@vilyapilya could you help us understand the latest code?  As we understand it, there is now a `flushAll()` command that will flush messages, but there is still no programmatic interface that would tell us when something has gone wrong and that we would need to call `flushAll()`.

The core problem was that there is no programmatic way of knowing if something has gone wrong, and so we cannot plug it in to any alerting system.  If the flushing fails, nothing tells us.  If the flushing fails and the buffer hits it's upper limit, nothing tells us and the library drops any new messages.  The only way of detecting these sorts of problems is if a human operator happens to notice that one of their applications hasn't logged recently, and even then they would struggle to prove whether the microservice is dropping logs or just not actually trying to log anything.

**Comment by darinspivey** [comment] 2020-07-17 14:44
Hi, @andyedwardsdfdl , sorry this response is late considering the history of this issue.  Our logger client is about to undergo some much needed "spring cleaning" where we can address things like this.  I see no reason that the `Logger` can't be an `EventEmitter` and give you what you need.  With the way that it buffers and retries, the use of callbacks doesn't work in all cases, so an emitter would make sense.

I will be releasing a `major` update soon to address some minor points, so this change could be worked into that, or possibly done soon after as a minor update.  Stay tuned, and thank you for this suggestion!

**Comment by darinspivey** [comment] 2020-08-25 18:38
@andyedwardsdfdl our new client has been released.  I think you'll find that the EventEmitter it implements is what you need.  Please refer to the README in our new package, [@logdna/logger](https://www.npmjs.com/package/@logdna/logger)

Feel free to open any issues under that new repository.  Thanks!

**Closed as completed by darinspivey** 2020-08-25 18:38 UTC
Labels: enhancement
